version: 2.1

executors:
  default:
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          TZ: "Asia/Tokyo"
  extend:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: user
          RAILS_ENV: test
          TZ: "Asia/Tokyo"
      - image: circleci/postgres:11.3-alpine
        environment:
          POSTGRES_USER: user
          POSTGRES_DB: prebill_test
          POSTGRES_PASSWORD: ""
          TZ: "Asia/Tokyo"

commands:
  restore_gems:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
  restore_yarn:
    steps:
      - restore_cache:
          keys:
            - rails-yarn-{{ checksum "yarn.lock" }}
            - rails-yarn-
  install_gems:
    steps:
      - run: gem install bundler
      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --clean --force --jobs=4 --retry=3
  install_yarn:
    steps:
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
  save_gems:
    steps:
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  save_yarn:
    steps:
      - save_cache:
          key: rails-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  rubocop:
    executor: default
    steps:
      - checkout
      - restore_gems
      - install_gems
      - save_gems
      - run:
          name: Run rubocop
          command: |
            bundle exec rubocop -c .rubocop.yml
  rspec:
    executor: extend
    steps:
      - checkout
      - restore_gems
      - restore_yarn
      - install_gems
      - install_yarn
      - save_gems
      - save_yarn
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace
      - run:
          name: Run RSpec
          command: |
            bundle exec rspec -b --format documentation
      - store_test_results:
          path: tmp/test-results

      - store_artifacts:
          path: tmp/screenshots
          destination: screenshots

workflows:
  version: 2.1
  rubocop-and-rspec:
    jobs:
      - rubocop
      - rspec
